server:
  port: 8080


spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Dialect for the database you are using
        format_sql: true # Formats SQL statements for better readability
      show-sql: true # Shows SQL statements in the logs
  datasource:
    url: jdbc:postgresql://localhost:5332/customer # URL for the database
    username: ak # Database username
    password: password # Database password
